import React,{useEffect,useState}from"react";
import PublicHeader from"../components/PublicHeader";
import{Link,useNavigate}from"react-router-dom";
import{api}from"../lib/api";
import{useColors}from"../context/ThemeContext";
import{TwIcon}from"../components/TwUI";

const checks=p=>({len:p.length>=8,upper:/[A-Z]/.test(p),lower:/[a-z]/.test(p),num:/[0-9]/.test(p),sym:/[^A-Za-z0-9]/.test(p)});
export default function ForgotPassword(){
 const nav=useNavigate(),c=useColors();
 const[step,setStep]=useState("email"),[email,setEmail]=useState(""),[code,setCode]=useState(""),[token,setToken]=useState(""),[pw,setPw]=useState(""),[confirm,setConfirm]=useState("");
 const[showPw,setShowPw]=useState(false),[showConfirm,setShowConfirm]=useState(false),[seconds,setSeconds]=useState(0),[notice,setNotice]=useState(null);
 const pc=checks(pw),strong=Object.values(pc).every(Boolean),matches=!!pw&&pw===confirm;
 useEffect(()=>{if(seconds<=0)return;const id=setInterval(()=>setSeconds(v=>Math.max(0,v-1)),1000);return()=>clearInterval(id)},[seconds]);
 function flash(text,type="error"){setNotice({text,type});}
 async function send(e){e?.preventDefault();setNotice(null);if(!/^\S+@\S+\.\S+$/.test(email))return flash("Enter a valid email address.");try{const{data}=await api.post("/auth/password/request-reset",{email:email.trim()});setStep("otp");setSeconds(30);setCode("");flash(data.emailSent?"OTP sent to your email.":data.devOtp?`Testing OTP: ${data.devOtp}`:(data.deliveryWarning||"OTP generated; check the server terminal."),"success")}catch(x){flash(x?.response?.data?.message||"Could not send OTP.")}}
 async function resend(){if(seconds>0)return;await send()}
 async function verify(e){e.preventDefault();setNotice(null);if(!/^\d{6}$/.test(code))return flash("Enter the six-digit OTP code.");try{const{data}=await api.post("/auth/password/verify-reset",{email:email.trim(),code});setToken(data.resetToken);setStep("password");setNotice(null)}catch(x){flash(x?.response?.data?.message||"Invalid or expired OTP.")}}
 async function reset(e){e.preventDefault();setNotice(null);if(!strong)return flash("Password must satisfy every requirement.");if(!matches)return flash("Passwords do not match.");try{await api.post("/auth/password/confirm-reset",{resetToken:token,newPassword:pw});flash("Password changed successfully.","success");setTimeout(()=>nav("/login"),1000)}catch(x){flash(x?.response?.data?.message||"Password reset failed.")}}
 return <div className="tw-starry-page tw-reset-page" style={{background:c.pageBg,color:c.text}}><PublicHeader compact hideSuper/><main className="tw-reset-main"><section className={`tw-reset-card ${step==="password"?"wide":""}`} style={{background:c.cardBg3,borderColor:c.border,color:c.text}}><div><h1>Reset Password</h1>{step!=="password"&&<p style={{color:c.textMuted}}>Verify your email before choosing a new password.</p>}{notice&&<div className={notice.type==="success"?"tw-reset-success":"tw-reset-error"}>{notice.text}</div>}
 {step==="email"&&<form onSubmit={send}><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="user@example.com" style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}/><button className="tw-auth-primary tw-reset-send" type="submit">Send OTP</button></form>}
 {step==="otp"&&<form onSubmit={verify}><label>OTP Code</label><div className="tw-otp-inline"><input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} placeholder="6-digit code" style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}/><button type="button" disabled={seconds>0} onClick={resend}>{seconds>0?`${seconds}s`:"Resend"}</button></div><button className="tw-auth-primary" type="submit">Verify OTP</button></form>}
 {step==="password"&&<form className="tw-reset-password-form" onSubmit={reset}><label>New password</label><div className="tw-password-row"><input type={showPw?"text":"password"} value={pw} onChange={e=>setPw(e.target.value)} required placeholder="Create a password" style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}/><button type="button" aria-label="Show password" onClick={()=>setShowPw(v=>!v)}><TwIcon name={showPw?"eyeOff":"eye"} size={19}/></button></div><label>Confirm password</label><div className="tw-password-row"><input type={showConfirm?"text":"password"} value={confirm} onChange={e=>setConfirm(e.target.value)} required placeholder="Confirm your password" style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}/><button type="button" aria-label="Show confirm password" onClick={()=>setShowConfirm(v=>!v)}><TwIcon name={showConfirm?"eyeOff":"eye"} size={19}/></button></div><button className="tw-auth-primary" type="submit">Change Password</button></form>}
 <p className="tw-reset-back"><Link to="/login">Back to login</Link></p></div>{step==="password"&&<aside className="tw-reset-requirements" style={{background:c.cardBg2,border:`1px solid ${c.border}`}}><h3>Password requirements</h3>{Object.entries({len:"At least 8 characters",upper:"At least 1 uppercase letter",lower:"At least 1 lowercase letter",num:"At least 1 number",sym:"At least 1 special character"}).map(([k,v])=><span className={pc[k]?"ok":""} key={k}>{pc[k]?"●":"○"} {v}</span>)}<div className="tw-reset-strength"><i style={{width:`${Object.values(pc).filter(Boolean).length*20}%`}}/></div><small>{strong?"Strong ✓":"Complete every requirement"}</small><span className={matches?"ok":""}>{matches?"●":"○"} Passwords match</span></aside>}</section></main></div>}
