import React,{useEffect,useMemo,useState} from "react";
import {useNavigate} from "react-router-dom";
import {api,setAuthToken} from "../../lib/api";
import {clearRole,clearToken} from "../../lib/auth";
import {ThemedModal,useColors,useTheme} from "../../context/ThemeContext";
import {TwIcon} from "../../components/TwUI";
import DashboardShell from "../../components/DashboardShell";
import {ProfileSettingsModal,ProfileSavedOverlay,useDashboardProfile} from "../../components/ProfileSettings";
import {LineChart,DonutChart,BarChart} from "../../components/SimpleCharts";

const NAV=[{id:"overview",label:"Overview",icon:"home"},{id:"institutions",label:"Institutions",icon:"classes"},{id:"notifications",label:"Notifications",icon:"bell"},{id:"health",label:"System Health",icon:"health"}];
const FILTERS=["ALL","PLAN_APPLICATION","USER_REGISTERED","INSTITUTION_SETUP","ACCOUNT_DELETED","PASSWORD_CHANGED","FEEDBACK"];
const card=(c,extra={})=>({background:c.cardBg,border:`1px solid ${c.border}`,borderRadius:18,padding:18,boxShadow:"0 18px 40px rgba(15,23,42,.07)",...extra});
const quiet=(c,extra={})=>({background:c.cardBg2,border:`1px solid ${c.border}`,borderRadius:14,padding:14,...extra});
const fmt=d=>d?new Date(d).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"}):"—";
const monthLabel=m=>{if(!m)return"";const [y,mo]=m.split("-");return new Date(Number(y),Number(mo)-1,1).toLocaleDateString("en-PH",{month:"short"})};

export default function SuperadminDashboard(){
  const nav=useNavigate();const c=useColors();const {dark,toggleTheme}=useTheme();const [activeTab,setActiveTab]=useState("overview");const [logout,setLogout]=useState(false);const profileState=useDashboardProfile();
  function doLogout(){clearToken();clearRole();setAuthToken("");nav("/")}
  return <><DashboardShell navItems={NAV} activeTab={activeTab} setActiveTab={setActiveTab} dark={dark} toggleTheme={toggleTheme} onLogout={()=>setLogout(true)} profile={profileState.profile} onProfile={()=>profileState.setProfileOpen(true)}>{activeTab==="overview"&&<Overview onOpenNotifications={()=>setActiveTab("notifications")}/>}{activeTab==="institutions"&&<Institutions/>}{activeTab==="notifications"&&<Notifications/>}{activeTab==="health"&&<Health/>}</DashboardShell>{profileState.profileOpen&&<ProfileSettingsModal roleLabel="Superadmin" showInstitution={false} profile={profileState.profile} setProfile={profileState.setProfile} onClose={()=>profileState.setProfileOpen(false)} onSaved={()=>{profileState.setSaved(true);setTimeout(()=>profileState.setSaved(false),2000)}}/>}{profileState.saved&&<ProfileSavedOverlay/>}{logout&&<ThemedModal icon={<TwIcon name="logout" size={30}/>} title="Log out?" message="Are you sure you want to log out of the superadmin dashboard?" onClose={()=>setLogout(false)}><button className="btn secondary" onClick={()=>setLogout(false)}>Cancel</button><button className="btn" style={{background:dark?"#7f1d1d":"#dc2626",color:"#fff"}} onClick={doLogout}>Yes, Log Out</button></ThemedModal>}</>;
}
function Heading({title}){const c=useColors();return <h2 style={{margin:"0 0 22px",color:c.text,fontSize:28,letterSpacing:"-.035em"}}>{title}</h2>}
function Metric({label,value,icon,tone="#2b6cff"}){const c=useColors();return <div className="tw-super-card" style={{...card(c),display:"flex",alignItems:"center",gap:14,padding:15}}><span style={{width:44,height:44,borderRadius:14,display:"grid",placeItems:"center",background:`${tone}18`,color:tone}}><TwIcon name={icon} size={22}/></span><div><b style={{display:"block",fontSize:27,color:c.text}}>{typeof value==="number"?value.toLocaleString():value??0}</b><small style={{color:c.textMuted,fontWeight:800}}>{label}</small></div></div>}
function ChartTitle({title,icon}){const c=useColors();return <div style={{display:"flex",alignItems:"center",gap:9,fontWeight:900,fontSize:17,color:c.text,marginBottom:14}}><TwIcon name={icon} size={20}/>{title}</div>}
function Info({label,value}){const c=useColors();return <div style={{display:"flex",justifyContent:"space-between",gap:12,padding:"12px 0",borderBottom:`1px solid ${c.border}`}}><span style={{color:c.textMuted}}>{label}</span><b style={{color:c.text,textAlign:"right"}}>{value??"—"}</b></div>}
function Empty({text}){const c=useColors();return <div style={{...quiet(c),color:c.textMuted,textAlign:"center"}}>{text}</div>}
function ApiMessage({text}){const c=useColors();return <div style={{...quiet(c),color:c.redFg,borderColor:c.redBorder,marginBottom:16}}>{text}</div>}
function LoadingCard({text}){const c=useColors();return <div style={{...card(c),color:c.textMuted,textAlign:"center"}}>{text}</div>}

function Overview({onOpenNotifications}){
  const c=useColors();const [stats,setStats]=useState(null);const [activity,setActivity]=useState([]);
  useEffect(()=>{api.get("/superadmin/stats").then(r=>setStats(r.data)).catch(()=>{});api.get("/superadmin/notifications?type=ALL").then(r=>setActivity(r.data||[])).catch(()=>{})},[]);
  const timeline=normalizeAccountWeeks(stats?.accountTimeline||[]);const session=stats?.sessionTimeline||[];
  return <div className="container"><Heading title="Superadmin Overview"/><div className="tw-overview-layout"><div className="tw-overview-metrics"><Metric label="Total Institutions" value={stats?.totalInstitutions} icon="classes"/><Metric label="Total Admins" value={stats?.totalAdmins} icon="user" tone="#8b5cf6"/><Metric label="Total Teachers" value={stats?.totalTeachers} icon="teacher" tone="#14b8a6"/><Metric label="Total Students" value={stats?.totalStudents} icon="student" tone="#f59e0b"/></div><div className="tw-overview-charts"><section style={card(c)}><ChartTitle title="Accounts Created Every Week" icon="chart"/><LineChart values={timeline.map(x=>x.total)} labels={timeline.map(x=>x.label)}/></section><section style={card(c)}><ChartTitle title="Account Distribution" icon="user"/><DonutChart data={stats?.accountDistribution||[]} centerLabel="Accounts"/></section><section style={card(c)}><ChartTitle title="Sessions by Month" icon="live"/><BarChart data={session.slice(-6).map(x=>({label:monthLabel(x.month),value:x.total}))}/></section></div></div><div className="tw-platform-bottom"><section style={card(c)}><div className="tw-section-title-action"><ChartTitle title="Recent Platform Activity" icon="history"/><button type="button" className="btn secondary" onClick={onOpenNotifications}>Open</button></div><div className="tw-scroll-activity tw-submission-scroll">{activity.slice(0,20).map(x=><Activity key={`${x.type}-${x.id}-${x.created_at}`} item={x}/>)}{!activity.length&&<Empty text="Recent platform activity will appear here."/>}</div></section><section style={card(c)}><ChartTitle title="Platform Insights" icon="chart"/><Info label="Active live sessions" value={stats?.activeLive}/><Info label="Paused live sessions" value={stats?.pausedLive}/><Info label="Completed this week" value={stats?.completedThisWeek}/><Info label="Institution coverage" value={`${stats?.totalInstitutions||0} connected`}/></section></div></div>;
}
function Activity({item}){const c=useColors();return <div className="tw-notification-row" style={quiet(c)}><span style={{color:c.accent}}><TwIcon name={notificationIcon(item.type)} size={21}/></span><div><b style={{color:c.text}}>{item.name||notificationLabel(item.type)}</b><p style={{color:c.textMuted}}>{notificationLabel(item.type)}{item.email?` · ${item.email}`:""}</p><small style={{color:c.textSub}}>{fmt(item.created_at)}</small></div></div>}

function Institutions(){
  const c=useColors();const [items,setItems]=useState([]);const [search,setSearch]=useState("");const [sort,setSort]=useState("az");const [expanded,setExpanded]=useState(null);const [confirm,setConfirm]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const load=()=>{setLoading(true);setError("");return api.get("/superadmin/accounts").then(r=>setItems(Array.isArray(r.data)?r.data:[])).catch(err=>{setItems([]);setError(err?.response?.data?.message||"Unable to load institutions.")}).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(x=>`${x?.name||""} ${x?.admin?.first_name||""} ${x?.admin?.last_name||""}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(sort==="az"?1:-1)*String(a?.name||"").localeCompare(String(b?.name||""))),[items,search,sort]);
  async function act(){if(!confirm)return;try{if(confirm.action==="remove")await api.delete(`/superadmin/accounts/${confirm.admin.id}`);else await api.post(`/superadmin/accounts/${confirm.admin.id}/active`,{active:false});setConfirm(null);await load()}catch(err){setError(err?.response?.data?.message||"Unable to update this administrator.");setConfirm(null)}}
  return <div className="container"><Heading title="Institutions"/><div className="tw-filter-row" style={card(c)}><div className="tw-search-input"><TwIcon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search institution or admin" style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}/></div><select value={sort} onChange={e=>setSort(e.target.value)} style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}><option value="az">Sort: A–Z</option><option value="za">Sort: Z–A</option></select></div>{error&&<ApiMessage text={error}/>}<div className="tw-super-institution-list">{loading?<LoadingCard text="Loading institutions…"/>:filtered.map(inst=><InstitutionCard key={inst.name||inst.admin?.id} inst={inst} expanded={expanded===inst.name} onToggle={()=>setExpanded(expanded===inst.name?null:inst.name)} onAction={setConfirm} c={c}/>)}{!loading&&!filtered.length&&<Empty text="No institutions found."/>}</div><ActionDialogSimple confirm={confirm} onClose={()=>setConfirm(null)} onConfirm={act}/></div>;
}
function InstitutionCard({inst,expanded,onToggle,onAction,c}){
  const admin=inst.admin;const inactive=Math.max(0,Number(inst.teacherCount||0)-Number(inst.activeTeacherCount||0));
  return <article className="tw-super-institution-card" style={{...card(c),padding:0,overflow:"hidden"}}><button type="button" onClick={onToggle} className="tw-super-institution-head" style={{color:c.text}}><div><h3>{inst.name||"Unnamed institution"}</h3><small style={{color:c.textMuted}}>{admin?`${admin.first_name||""} ${admin.last_name||""} · ${admin.email||"No email"}`:"No assigned admin"}</small></div><TwIcon name={expanded?"chevronUp":"chevronDown"} size={22}/></button>{expanded&&<div className="tw-super-institution-expanded" style={{borderColor:c.border}}><div className="tw-super-admin-row"><div><small style={{color:c.textMuted}}>Institution administrator</small><h3 style={{color:c.text}}>{admin?`${admin.first_name||""} ${admin.last_name||""}`:"No assigned admin"}</h3></div>{admin&&<div><button className="btn secondary" onClick={()=>onAction({action:"deactivate",admin})}>Deactivate Admin</button><button className="btn" style={{background:c.redBg,color:c.redFg,border:`1px solid ${c.redBorder}`}} onClick={()=>onAction({action:"remove",admin})}>Remove Admin</button></div>}</div><div className="tw-super-institution-detail-grid"><div style={quiet(c)}><Info label="Total teachers" value={inst.teacherCount||0}/><Info label="Active teachers" value={inst.activeTeacherCount||0}/><Info label="Total students" value={inst.studentCount||0}/><Info label="Total classes" value={inst.classCount||0}/><Info label="Total live sessions" value={inst.liveSessionCount||0}/><Info label="Total assigned sessions" value={inst.assignedSessionCount||0}/></div><section style={quiet(c)}><ChartTitle title="Teacher activity" icon="teacher"/><DonutChart data={[{label:"Active",value:Number(inst.activeTeacherCount||0)},{label:"Inactive",value:inactive}]} centerLabel="Teachers"/></section><section style={quiet(c)}><ChartTitle title="Session totals" icon="live"/><BarChart data={[{label:"Live",value:Number(inst.liveSessionCount||0)},{label:"Assigned",value:Number(inst.assignedSessionCount||0)}]} height={190}/></section><section style={quiet(c)}><ChartTitle title="Institution reach" icon="classes"/><BarChart data={[{label:"Classes",value:Number(inst.classCount||0)},{label:"Students",value:Number(inst.studentCount||0)}]} height={190}/></section></div></div>}</article>;
}
function ActionDialogSimple({confirm,onClose,onConfirm}){const c=useColors();if(!confirm)return null;return <ThemedModal open={!!confirm} icon={<TwIcon name={confirm?.action==="remove"?"trash":"warning"} size={28}/>} title={confirm?.action==="remove"?"Remove this administrator?":"Deactivate this administrator?"} message={confirm?.action==="remove"?"The account will be removed from active platform use.":"The administrator will no longer be able to access the institution dashboard."} onClose={onClose}>{confirm&&<><button className="btn secondary" onClick={onClose}>Cancel</button><button className="btn" style={{background:c.redBg,color:c.redFg,border:`1px solid ${c.redBorder}`}} onClick={onConfirm}>Confirm</button></>}</ThemedModal>}

function Notifications(){
  const c=useColors();const [items,setItems]=useState([]);const [search,setSearch]=useState("");const [type,setType]=useState("ALL");const [open,setOpen]=useState(null);
  const load=()=>api.get(`/superadmin/notifications?type=${encodeURIComponent(type)}&search=${encodeURIComponent(search)}`).then(r=>setItems(r.data||[])).catch(()=>setItems([]));
  useEffect(()=>{const timer=setTimeout(load,180);return()=>clearTimeout(timer)},[search,type]);
  async function review(item,decision){const id=item.payload?.applicationId;if(!id||item.status!=="NEW")return;const nextStatus=decision==="APPROVED"?"APPROVED":"DISAPPROVED";setItems(rows=>rows.map(row=>row.id===item.id&&row.legacy===item.legacy?{...row,status:nextStatus}:row));try{await api.post(`/superadmin/applications/${id}/review`,{decision});await load()}catch{setItems(rows=>rows.map(row=>row.id===item.id&&row.legacy===item.legacy?{...row,status:"NEW"}:row))}}
  return <div className="container"><Heading title="Notifications"/><div className="tw-filter-row" style={card(c)}><div className="tw-search-input"><TwIcon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search notifications" style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}/></div><select value={type} onChange={e=>setType(e.target.value)} style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}>{FILTERS.map(x=><option key={x} value={x}>{x==="ALL"?"All notification types":notificationLabel(x)}</option>)}</select></div><div style={{display:"grid",gap:12,marginTop:18}}>{items.map(item=>{const isApp=item.type==="PLAN_APPLICATION";const key=`${item.id}-${item.legacy?"l":"n"}`;const isOpen=open===key;return <article key={key} className="tw-super-card" style={card(c,{padding:0,overflow:"hidden"})}><button className="tw-notification-head" onClick={()=>isApp&&setOpen(isOpen?null:key)} style={{color:c.text}}><span style={{color:c.accent}}><TwIcon name={notificationIcon(item.type)} size={22}/></span><div><b>{notificationLabel(item.type)}</b><small style={{color:c.textMuted}}>{item.name||"ThinkWAVE user"} · {fmt(item.created_at)}</small></div>{isApp&&<TwIcon name={isOpen?"chevronUp":"chevronDown"}/>}</button>{isApp&&isOpen&&<div className="tw-application-details" style={{background:c.cardBg2,borderColor:c.border}}>{[["First name",item.payload?.firstName],["Last name",item.payload?.lastName],["Work email",item.payload?.workEmail],["Country",item.payload?.country],["Role",item.payload?.role],["Phone number",item.payload?.phone]].map(([label,value])=><div key={label} className="tw-application-field"><small>{label}:</small><b>{value||"—"}</b></div>)}<div className="tw-application-actions"><button className="btn" style={{background:c.redBg,color:c.redFg,border:`1px solid ${c.redBorder}`}} disabled={item.status!=="NEW"} onClick={()=>review(item,"DISAPPROVED")}>{item.status==="DISAPPROVED"?"Disapproved":"Disapprove"}</button><button className="btn" disabled={item.status!=="NEW"} onClick={()=>review(item,"APPROVED")}>{item.status==="APPROVED"?"Approved":"Approve"}</button></div></div>}</article>})}{!items.length&&<Empty text="No notifications match the current filters."/>}</div></div>;
}

function Health(){
  const c=useColors();const [data,setData]=useState(null);useEffect(()=>{const load=()=>api.get("/superadmin/health").then(r=>setData(r.data)).catch(()=>{});load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[]);const history=data?.history||[];
  return <div className="container"><Heading title="System Health"/><div className="tw-health-grid"><section style={card(c)}><ChartTitle title="Server Details" icon="server"/><Info label="Platform" value={data?.server?.platform}/><Info label="Node version" value={data?.server?.nodeVersion}/><Info label="CPU model" value={data?.server?.cpuModel}/><Info label="CPU usage" value={`${data?.server?.cpuUsage||0}%`}/><Info label="Memory usage" value={`${data?.server?.memoryUsage||0}%`}/><Info label="Uptime" value={formatUptime(data?.server?.uptimeSec)}/><Info label="Database" value={data?.database?.connected?"Connected":"Unavailable"}/></section><section style={card(c)}><ChartTitle title="Live Performance" icon="traffic"/><div className="tw-health-metrics"><Metric label="Latency" value={`${data?.live?.latencyMs||0} ms`} icon="clock"/><Metric label="Errors" value={data?.live?.errorCount||0} icon="error" tone="#ef4444"/><Metric label="Requests" value={data?.live?.requestCount||0} icon="traffic" tone="#f59e0b"/></div><BarChart data={history.slice(-12).map((row,index)=>({label:index===Math.min(11,history.slice(-12).length-1)?"Now":"",value:Number(row.requests||0)}))} height={220}/></section></div></div>;
}
function formatUptime(sec){const value=Number(sec||0);const days=Math.floor(value/86400);const hours=Math.floor((value%86400)/3600);const minutes=Math.floor((value%3600)/60);return `${days}d ${hours}h ${minutes}m`}
function notificationLabel(type){return({PLAN_APPLICATION:"Institution Plan application",USER_REGISTERED:"New user registration",INSTITUTION_SETUP:"Institution setup",ACCOUNT_DELETED:"Account deleted",PASSWORD_CHANGED:"Password changed",FEEDBACK:"User feedback"}[type]||String(type||"Platform activity").replaceAll("_"," "))}
function normalizeAccountWeeks(rows){const normalized=(rows||[]).map(row=>({weekStart:row.weekStart||row.week_start,total:Number(row.total||0)}));const map=new Map(normalized.map(row=>[String(row.weekStart||"").slice(0,10),row]));const now=new Date();const monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(now.getDate()-((now.getDay()+6)%7));return Array.from({length:12},(_,index)=>{const date=new Date(monday);date.setDate(monday.getDate()-(11-index)*7);const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;const row=map.get(key)||{};return{weekStart:key,label:date.toLocaleDateString("en-PH",{month:"short",day:"numeric"}),total:Number(row.total||0)}})}
function notificationIcon(type){return({PLAN_APPLICATION:"mail",USER_REGISTERED:"user",INSTITUTION_SETUP:"classes",ACCOUNT_DELETED:"trash",PASSWORD_CHANGED:"lock",FEEDBACK:"message"}[type]||"bell")}
