import React,{useEffect,useMemo,useState} from "react";
import {useNavigate} from "react-router-dom";
import {api,setAuthToken} from "../../lib/api";
import {clearRole,clearToken} from "../../lib/auth";
import {ThemedModal,useColors,useTheme} from "../../context/ThemeContext";
import {TwIcon} from "../../components/TwUI";
import DashboardShell from "../../components/DashboardShell";
import {ProfileSettingsModal,ProfileSavedOverlay,useDashboardProfile} from "../../components/ProfileSettings";
import {DualLineChart,DonutChart,BarChart} from "../../components/SimpleCharts";

const NAV=[{id:"overview",label:"Overview",icon:"home"},{id:"teachers",label:"Teachers",icon:"teacher"},{id:"institution",label:"Institution",icon:"classes"},{id:"invitation",label:"Invitation",icon:"invitation"}];
const card=(c,extra={})=>({background:c.cardBg,border:`1px solid ${c.border}`,borderRadius:18,padding:18,boxShadow:"0 18px 40px rgba(15,23,42,.07)",...extra});
const quiet=(c,extra={})=>({background:c.cardBg2,border:`1px solid ${c.border}`,borderRadius:14,padding:14,...extra});
const fmt=d=>d?new Date(d).toLocaleString("en-PH",{dateStyle:"medium",timeStyle:"short"}):"—";
const weekLabel=value=>value?new Date(value).toLocaleDateString("en-PH",{month:"short",day:"numeric"}):"";

export default function AdminDashboard(){const nav=useNavigate();const c=useColors();const {dark,toggleTheme}=useTheme();const [activeTab,setActiveTab]=useState("overview");const [setupDone,setSetupDone]=useState(true);const [institution,setInstitution]=useState("");const [setupName,setSetupName]=useState("");const [setupError,setSetupError]=useState("");const [logout,setLogout]=useState(false);const profileState=useDashboardProfile();
useEffect(()=>{api.get("/admin-dashboard/setup-status").then(({data})=>{setSetupDone(data.setupDone??true);setInstitution(data.institutionName||"")}).catch(()=>{})},[]);
async function saveSetup(){if(!setupName.trim())return;try{await api.post("/admin-dashboard/setup-institution",{institutionName:setupName.trim()});setInstitution(setupName.trim());setSetupDone(true)}catch(e){setSetupError(e?.response?.data?.message||"Failed to save institution name.")}}
function doLogout(){clearToken();clearRole();setAuthToken("");nav("/")}
if(!setupDone)return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",background:c.pageBg,padding:24}}><div style={card(c,{width:"min(100%,470px)",padding:34,textAlign:"center"})}><TwIcon name="classes" size={42} style={{color:c.accent}}/><h2 style={{color:c.text}}>Complete your institution setup</h2><p style={{color:c.textMuted,lineHeight:1.6}}>Enter your school or institution name to organize teachers, students, and activity under one shared profile.</p><input value={setupName} onChange={e=>setSetupName(e.target.value)} placeholder="Institution name" style={{width:"100%",boxSizing:"border-box",padding:14,borderRadius:13,border:`1px solid ${c.inputBorder}`,background:c.inputBg,color:c.text}}/>{setupError&&<p style={{color:c.redFg}}>{setupError}</p>}<button className="btn" style={{width:"100%",marginTop:14}} onClick={saveSetup}>Save and Continue</button></div></div>;
return <><DashboardShell navItems={NAV} activeTab={activeTab} setActiveTab={setActiveTab} dark={dark} toggleTheme={toggleTheme} onLogout={()=>setLogout(true)} profile={profileState.profile} onProfile={()=>profileState.setProfileOpen(true)}>{activeTab==="overview"&&<Overview/>}{activeTab==="teachers"&&<Teachers/>}{activeTab==="institution"&&<Institution/>}{activeTab==="invitation"&&<Invitation/>}</DashboardShell>
{profileState.profileOpen&&<ProfileSettingsModal roleLabel="Admin" profile={profileState.profile} setProfile={profileState.setProfile} onClose={()=>profileState.setProfileOpen(false)} onSaved={()=>{profileState.setSaved(true);setTimeout(()=>profileState.setSaved(false),2000)}}/>}{profileState.saved&&<ProfileSavedOverlay/>}{logout&&<ThemedModal icon={<TwIcon name="logout" size={30}/>} title="Log out?" message="Are you sure you want to log out of the admin dashboard?" onClose={()=>setLogout(false)}><button className="btn secondary" onClick={()=>setLogout(false)}>Cancel</button><button className="btn" style={{background:dark?"#7f1d1d":"#dc2626",color:"#fff"}} onClick={doLogout}>Yes, Log Out</button></ThemedModal>}</>}

function Heading({title}){const c=useColors();return <h2 style={{margin:"0 0 22px",color:c.text,fontSize:28,letterSpacing:"-.035em"}}>{title}</h2>}
function Metric({label,value,icon,tone="#2b6cff"}){const c=useColors();return <div className="tw-admin-card" style={{...card(c),display:"flex",alignItems:"center",gap:14,padding:15}}><span style={{width:44,height:44,borderRadius:14,display:"grid",placeItems:"center",background:`${tone}18`,color:tone}}><TwIcon name={icon} size={22}/></span><div><b style={{display:"block",fontSize:27,color:c.text}}>{Number(value||0).toLocaleString()}</b><small style={{color:c.textMuted,fontWeight:800}}>{label}</small></div></div>}
function ChartTitle({title,icon}){const c=useColors();return <div style={{display:"flex",alignItems:"center",gap:9,fontWeight:900,fontSize:17,color:c.text,marginBottom:14}}><TwIcon name={icon} size={20}/>{title}</div>}
function Info({label,value}){const c=useColors();return <div style={{display:"flex",justifyContent:"space-between",gap:12,padding:"12px 0",borderBottom:`1px solid ${c.border}`}}><span style={{color:c.textMuted}}>{label}</span><b style={{color:c.text,textAlign:"right"}}>{value??"—"}</b></div>}
function Empty({text}){const c=useColors();return <div style={{...quiet(c),color:c.textMuted,textAlign:"center"}}>{text}</div>}

function Overview(){
  const c=useColors();
  const [data,setData]=useState(null);
  const [error,setError]=useState("");
  useEffect(()=>{let alive=true;api.get("/admin-dashboard/stats").then(r=>{if(alive)setData(r.data||{})}).catch(err=>{if(alive)setError(err?.response?.data?.message||"Unable to load the admin overview.")});return()=>{alive=false}},[]);
  const weekly=Array.isArray(data?.weeklySessions)?data.weeklySessions:[];
  return <div className="container"><Heading title="Admin Overview"/>{error&&<ApiMessage text={error}/>}<div className="tw-overview-layout"><div className="tw-overview-metrics"><Metric label="Active Teachers" value={data?.activeTeachers} icon="teacher"/><Metric label="Active Live Sessions" value={data?.activeLiveSessions} icon="live" tone="#14b8a6"/><Metric label="Active Assigned Sessions" value={data?.activeAssignedSessions} icon="calendar" tone="#8b5cf6"/><Metric label="Active Students" value={data?.activeStudents} icon="student" tone="#f59e0b"/></div><div className="tw-overview-charts"><section style={card(c)}><ChartTitle title="Live and Assigned Sessions by Week" icon="chart"/><DualLineChart seriesA={weekly.map(x=>x.live)} seriesB={weekly.map(x=>x.assigned)} labels={weekly.map(x=>weekLabel(x.weekStart))} labelA="Live sessions" labelB="Assigned sessions"/></section><section style={card(c)}><ChartTitle title="Institution Account Mix" icon="user"/><DonutChart data={Array.isArray(data?.accountDistribution)?data.accountDistribution:[]} centerLabel="Members"/></section><section style={card(c)}><ChartTitle title="Template Usage" icon="bank"/><BarChart data={(Array.isArray(data?.templateUsage)?data.templateUsage:[]).map(x=>({label:String(x.label||"").replaceAll("_"," "),value:Number(x.value||0)}))}/></section></div></div></div>
}

function Teachers(){
  const c=useColors();
  const [items,setItems]=useState([]);
  const [search,setSearch]=useState("");
  const [selected,setSelected]=useState(null);
  const [confirm,setConfirm]=useState(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const load=()=>{setLoading(true);setError("");return api.get("/admin-dashboard/teachers").then(r=>{const rows=Array.isArray(r.data)?r.data:[];setItems(rows);setSelected(cur=>cur?(rows.find(x=>Number(x.id)===Number(cur.id))||null):null)}).catch(err=>{setItems([]);setSelected(null);setError(err?.response?.data?.message||"Unable to load teachers.")}).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(x=>`${x?.first_name||""} ${x?.last_name||""} ${x?.email||""}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
  async function toggle(){if(!confirm)return;try{await api.post(`/admin-dashboard/teachers/${confirm.teacher.id}/active`,{active:confirm.action==="activate"});setConfirm(null);await load()}catch(err){setError(err?.response?.data?.message||"Unable to update this teacher.");setConfirm(null)}}
  return <div className="container"><Heading title="Teachers"/><div className="tw-filter-row" style={card(c)}><div className="tw-search-input"><TwIcon name="search" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search teacher" style={{background:c.inputBg,color:c.text,borderColor:c.inputBorder}}/></div></div>{error&&<ApiMessage text={error}/>}<div className="tw-admin-two-panel"><section style={card(c)}>{loading?<LoadingCard text="Loading teachers…"/>:<div style={{display:"grid",gap:10}}>{filtered.map(t=><button key={t.id} className="tw-teacher-row" onClick={()=>setSelected(t)} style={{...quiet(c),color:c.text,borderColor:selected?.id===t.id?c.accent:c.border}}><div><b>{t.last_name||""}, {t.first_name||""}</b><small style={{color:c.textMuted}}>{t.email||"No email"}</small></div><span style={{color:t.is_active?c.greenFg:c.textMuted}}>{t.is_active?"Active":"Inactive"}</span></button>)}{!filtered.length&&<Empty text="No teachers found."/>}</div>}</section><section style={card(c)}><ChartTitle title="Teacher Details" icon="teacher"/>{selected?<><div style={quiet(c)}><h3 style={{color:c.text,margin:"0 0 5px"}}>{selected.first_name} {selected.last_name}</h3><p style={{color:c.textMuted,margin:0}}>{selected.email}</p></div><Info label="Joined" value={fmt(selected.created_at)}/><Info label="Last active" value={fmt(selected.last_active_at)}/><Info label="Hosted sessions" value={selected.hosted_sessions_count||0}/><Info label="Assigned sessions" value={selected.assigned_sessions_count||0}/><Info label="Last hosted session" value={fmt(selected.last_session_at)}/><Info label="Classes handled" value={selected.classes_handled_count||0}/><div style={{display:"flex",justifyContent:"center",gap:10,marginTop:18}}><button className="btn secondary" onClick={()=>setConfirm({teacher:selected,action:selected.is_active?"deactivate":"activate"})}>{selected.is_active?"Deactivate Teacher":"Activate Teacher"}</button></div></>:<Empty text="Select a teacher to view details."/>}</section></div>{confirm&&<ThemedModal icon={<TwIcon name="alert" size={30}/>} title={confirm.action==="deactivate"?"Deactivate Teacher?":"Activate Teacher?"} message={`${confirm.action==="deactivate"?"Deactivate":"Activate"} ${confirm.teacher.first_name} ${confirm.teacher.last_name}?`} onClose={()=>setConfirm(null)}><button className="btn secondary" onClick={()=>setConfirm(null)}>Cancel</button><button className="btn" onClick={toggle}>Confirm</button></ThemedModal>}</div>
}

function Institution(){
  const c=useColors();
  const [data,setData]=useState(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  useEffect(()=>{let alive=true;api.get("/admin-dashboard/institution").then(r=>{if(alive)setData(r.data||{})}).catch(err=>{if(alive)setError(err?.response?.data?.message||"Unable to load institution details.")}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[]);
  const inst=data?.institution||{};
  const teachers=Array.isArray(data?.teachers)?data.teachers:[];
  const activity=Array.isArray(data?.recentActivity)?data.recentActivity:[];
  return <div className="container"><Heading title="Institution"/>{error&&<ApiMessage text={error}/>} {loading?<LoadingCard text="Loading institution details…"/>:<div className="tw-admin-institution-grid"><section style={card(c)}><ChartTitle title="Institution Overview" icon="classes"/><Info label="Institution" value={inst.name}/><Info label="Administrator" value={inst.adminName}/><Info label="Admin email" value={inst.adminEmail}/><Info label="Total teachers" value={inst.totalTeachers||0}/><Info label="Total students" value={inst.totalStudents||0}/><Info label="Total hosted sessions this week" value={inst.hostedSessionsThisWeek||0}/><Info label="Total assigned sessions this week" value={inst.assignedSessionsThisWeek||0}/><Info label="Created" value={fmt(inst.createdAt)}/></section><div style={{display:"grid",gap:18}}><section style={card(c)}><ChartTitle title="Joined Teachers" icon="teacher"/><div style={{display:"grid",gap:9}}>{teachers.map(t=><div key={t.id} style={quiet(c)}><b style={{color:c.text}}>{t.last_name}, {t.first_name}</b><div style={{color:c.textMuted,fontSize:13,marginTop:4}}>{t.email}</div></div>)}{!teachers.length&&<Empty text="No teachers joined this institution yet."/>}</div></section><section style={card(c)}><ChartTitle title="Recent Institution Activity" icon="history"/><div className="tw-scroll-activity tw-submission-scroll">{activity.map((x,i)=><div key={`${x.kind}-${i}`} style={quiet(c)}><b style={{color:c.text}}>{x.title}</b><p style={{color:c.textMuted,margin:"4px 0"}}>{x.detail}</p><small style={{color:c.textSub}}>{fmt(x.event_at)}</small></div>)}{!activity.length&&<Empty text="Recent institution activity will appear here."/>}</div></section></div></div>}</div>
}

function Invitation(){
  const c=useColors();
  const [invite,setInvite]=useState(null);
  const [loading,setLoading]=useState(true);
  const [msg,setMsg]=useState("");
  const [error,setError]=useState("");
  const load=()=>{setLoading(true);setError("");return api.get("/admin-dashboard/invitation").then(r=>setInvite(r.data||null)).catch(err=>{setInvite(null);setError(err?.response?.data?.message||"Unable to load invitation details.")}).finally(()=>setLoading(false))};
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!msg)return;const t=setTimeout(()=>setMsg(""),2000);return()=>clearTimeout(t)},[msg]);
  async function generate(){try{setError("");const {data}=await api.post("/admin-dashboard/invitation",{});setInvite(data||null);setMsg("A fresh invitation code is now active.")}catch(e){setError(e?.response?.data?.message||"Failed to generate invitation code.")}}
  async function revoke(){if(!invite)return;try{await api.delete(`/admin-dashboard/invitation/${invite.id}`);setInvite(null);setMsg("Invitation code revoked.")}catch(e){setError(e?.response?.data?.message||"Failed to revoke invitation code.")}}
  return <div className="container"><Heading title="Invitation"/>{error&&<ApiMessage text={error}/>} {loading?<LoadingCard text="Loading invitation details…"/>:<div className="tw-admin-invitation-grid"><section style={card(c)}><ChartTitle title="Teacher Invitation Code" icon="invitation"/>{msg&&<div className="tw-fade-notice" style={{...quiet(c),color:c.greenFg,borderColor:c.greenBorder}}>{msg}</div>}{invite?<><div style={{...quiet(c),textAlign:"center",padding:28,background:"linear-gradient(135deg,rgba(43,108,255,.18),rgba(59,130,246,.08))"}}><small style={{color:c.textMuted}}>Active code</small><div style={{color:c.accent,fontSize:42,fontWeight:950,letterSpacing:8,marginTop:8}}>{invite.invite_code}</div></div><div style={{display:"flex",gap:10,marginTop:16}}><button className="btn secondary" style={{flex:1}} onClick={generate}>Regenerate</button><button className="btn" style={{flex:1,background:c.redBg,color:c.redFg,border:`1px solid ${c.redBorder}`}} onClick={revoke}>Revoke</button></div></>:<div style={{...quiet(c),textAlign:"center",padding:34}}><p style={{color:c.textMuted}}>No active invitation code yet.</p><button className="btn" onClick={generate}>Generate Code</button></div>}</section><section style={card(c)}><ChartTitle title="Quick Notes" icon="spark"/><div style={{display:"grid",gap:10}}><div style={quiet(c)}>Only one active code is kept at a time.</div><div style={quiet(c)}>Regenerating a code makes the previous code invalid.</div><div style={quiet(c)}>Share the code only with teachers who should join your institution.</div></div></section></div>}</div>
}

function ApiMessage({text}){const c=useColors();return <div style={{...quiet(c),margin:"0 0 16px",color:c.redFg,borderColor:c.redBorder,background:c.redBg}}><TwIcon name="alert" size={18}/> <span>{text}</span></div>}
function LoadingCard({text}){const c=useColors();return <div style={{...quiet(c),color:c.textMuted,textAlign:"center"}}>{text}</div>}
