import { BuilderTopBar } from "./BuilderTopBar";
import { BuilderPager } from "./BuilderPager";
import { BuilderSettingsSheet, BuilderOverflowSheet } from "./BuilderSheets";

export function BuilderHeader({
  isMobile,
  ui,
  quiz,
  titleDraft,
  setTitleDraft,
  titleEditing,
  setTitleEditing,
  titleSaving,
  saveTitle,
  truncatedQuizTitle,
  fullQuizTitle,
  guestMode,
  navigate,
  settingsOpen,
  setSettingsOpen,
  openSettings,
  overflowOpen,
  setOverflowOpen,
  openOverflow,
  builderTutorialStage,
  setBuilderTutorialStage,
  overflowTitleEditing,
  setOverflowTitleEditing,
  setQMenuOpen,
  questionStripOpen,
  closeQuestionStrip,
  toggleQuestionStrip,
  builderSettingsRows,
  isBatchTemplate,
  setModal,
  setBankOpen,
  addQuestion,
  requestSave,
  publish,
  isSaved,
  isSaving,
  publishLatched,
  publishDisabled,
  qIndex,
  navTick,
  totalQ,
  navDir,
  goPrev,
  goNext,
  isFirst,
  isLast,
  builderActionBorder,
  builderActionFace,
  builderTemplateAccent,
}) {
  return (
    <>
      <div style={ui.stickyHead}>
        <BuilderTopBar
          isMobile={isMobile}
          ui={ui}
          quiz={quiz}
          titleDraft={titleDraft}
          setTitleDraft={setTitleDraft}
          titleEditing={titleEditing}
          setTitleEditing={setTitleEditing}
          titleSaving={titleSaving}
          saveTitle={saveTitle}
          truncatedQuizTitle={truncatedQuizTitle}
          fullQuizTitle={fullQuizTitle}
          guestMode={guestMode}
          navigate={navigate}
          settingsOpen={settingsOpen}
          setSettingsOpen={setSettingsOpen}
          openSettings={openSettings}
          overflowOpen={overflowOpen}
          openOverflow={openOverflow}
          setOverflowOpen={setOverflowOpen}
          builderTutorialStage={builderTutorialStage}
          setBuilderTutorialStage={setBuilderTutorialStage}
          setOverflowTitleEditing={setOverflowTitleEditing}
          setQMenuOpen={setQMenuOpen}
          questionStripOpen={questionStripOpen}
          closeQuestionStrip={closeQuestionStrip}
          builderSettingsRows={builderSettingsRows}
          isBatchTemplate={isBatchTemplate}
          setModal={setModal}
          setBankOpen={setBankOpen}
          addQuestion={addQuestion}
          requestSave={requestSave}
          publish={publish}
          isSaved={isSaved}
          isSaving={isSaving}
          publishLatched={publishLatched}
          publishDisabled={publishDisabled}
        />

        <BuilderPager
          isMobile={isMobile}
          ui={ui}
          questionStripOpen={questionStripOpen}
          toggleQuestionStrip={toggleQuestionStrip}
          qIndex={qIndex}
          navTick={navTick}
          totalQ={totalQ}
          navDir={navDir}
          isBatchTemplate={isBatchTemplate}
          goPrev={goPrev}
          goNext={goNext}
          isFirst={isFirst}
          isLast={isLast}
          builderActionBorder={builderActionBorder}
          builderActionFace={builderActionFace}
          builderTemplateAccent={builderTemplateAccent}
        />
      </div>

      {isMobile && settingsOpen && (
        <BuilderSettingsSheet builderSettingsRows={builderSettingsRows} ui={ui} setSettingsOpen={setSettingsOpen} />
      )}
      {isMobile && overflowOpen && (
        <BuilderOverflowSheet
          ui={ui}
          quiz={quiz}
          titleDraft={titleDraft}
          setTitleDraft={setTitleDraft}
          overflowTitleEditing={overflowTitleEditing}
          setOverflowTitleEditing={setOverflowTitleEditing}
          titleSaving={titleSaving}
          saveTitle={saveTitle}
          truncatedQuizTitle={truncatedQuizTitle}
          fullQuizTitle={fullQuizTitle}
          guestMode={guestMode}
          setBankOpen={setBankOpen}
          setOverflowOpen={setOverflowOpen}
          requestSave={requestSave}
          publish={publish}
          isSaved={isSaved}
          isSaving={isSaving}
          publishDisabled={publishDisabled}
          publishLatched={publishLatched}
          builderTutorialStage={builderTutorialStage}
          setModal={setModal}
        />
      )}
    </>
  );
}
